# Generated by Django 4.1.1 on 2022-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorReq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorreq',
            name='web',
        ),
        migrations.AddField(
            model_name='donorreq',
            name='hospital',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
